### ISSUE TITLE
No module named 'brainpy._c.composition'

### ISSUE THREAD

**Issue by yhu39** [mobiusklein/brainpy#5]
I downloaded the code from github and tried to install it by using python setup.py install
When I tried to use "from brainpy import isotopic_variants", the error message is "No module named 'brainpy._c.composition'".
I don't know how to deal with this. Please help.
Thanks!

**Comment by mobiusklein** [comment]
Thank you for reporting this. It reminds me I didn't put the note about requiring Cython to  install from source. `brainpy` has two C-based implementations, a Cython-ized version of the pure Python implementation, and a pure C implementation with Python bindings, both built with Cython.

To install from source, please install a recent version of Cython and have a C compiler appropriate to your Python version installed. Alternatively, if you're on Windows where it's difficult to obtain a C compiler, you can install this package using the prebuilt wheels available on PyPI using `pip install brain-isotopic-distribution` for Python versions 3.5-3.8. The package name `brainpy` was already taken.

**Comment by mobiusklein** [comment]
I've updated the documentation to reflect this.

**Comment by mobiusklein** [comment]
@yhu39 Have I solved the issue and can close this?

**Comment by yhu39** [comment]
Sure. Thank you very much!
